/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package halaman;
import java.awt.Color;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
//import com.toedter.calendar.JDateChooser;

/**
 *
 * @author riogesta
 */
public class UangKas extends javax.swing.JFrame {

    /**
     * Creates new form UangKas
     */
    
    // variabel nama1-3
    public String name1 = "Fitri Destiyanti - 3411191121";
    public String name2 = "Salsabila Fajriati - 3411191119";
    public String name3 = "Rio Gestavito - 3411191129";
    
    static boolean maximized = true;
    int Xmouse;
    int Ymouse;
    
    DefaultTableModel model;
    DefaultTableModel model2;
    
    
    
    public UangKas() {
        initComponents();
        String [] fieldMasuk = {"Kode", "Nama pembayar", "Uang masuk","Tanggal masuk"};
        model = new DefaultTableModel(fieldMasuk, 0);
        tabelMasuk.setModel(model);
        
        String fieldKeluar [] = {"Kode", "Uang keluar", "Keperluan", "Tanggal"};
        model2 = new DefaultTableModel(fieldKeluar, 0);
        tabelKeluar.setModel(model2);
        
        //jDateChooser
        
        
        
        
        // menampilkan total uang masuk dan keluar
        uang_masuk();
        uang_keluar();
        
        tampilkan();
        tampilkan_uang_keluar();
    }
    
    public String getNamesatu(){
        return this.name1;
    }
    public String getNamedua(){
        return this.name2;
    }
    
    public String getNametiga(){
        return this.name3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnHide = new javax.swing.JButton();
        labelInfo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        lineRingkasan = new javax.swing.JLabel();
        lineUangmasuk = new javax.swing.JLabel();
        lineUangkeluar = new javax.swing.JLabel();
        menuUangkeluar = new javax.swing.JButton();
        menuUangmasuk = new javax.swing.JButton();
        menuRingkasan = new javax.swing.JButton();
        pnlBody = new javax.swing.JPanel();
        cardRingkasan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelTotalUangKeluar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelTotalUangMasuk = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelSisaUang = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelTotalUang_img = new javax.swing.JLabel();
        panelHeader_totaluang_img = new javax.swing.JLabel();
        labelTotalUang_img1 = new javax.swing.JLabel();
        panelHeader_totaluang_img1 = new javax.swing.JLabel();
        panelHeader_totaluang_img2 = new javax.swing.JLabel();
        labelTotalUang_img2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cardUangmasuk = new javax.swing.JPanel();
        TFbayar = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        TFkode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TFnama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMasuk = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnCariMasuk = new javax.swing.JButton();
        TFCariMasuk = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        cardUangkeluar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TAKeperluan = new javax.swing.JTextArea();
        TFTerpakai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelKeluar = new javax.swing.JTable();
        btnPake = new javax.swing.JButton();
        btnEditPake = new javax.swing.JButton();
        TFkode_keluar = new javax.swing.JTextField();
        btnHapusKeluar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        TFCariK = new javax.swing.JTextField();
        btnCariKeluar = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Uang masuk");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(121, 163, 177));
        panelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelHeaderMouseDragged(evt);
            }
        });
        panelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelHeaderMousePressed(evt);
            }
        });
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setBackground(new java.awt.Color(121, 163, 177));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnExit.setContentAreaFilled(false);
        btnExit.setFocusable(false);
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        panelHeader.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 32, 31));

        btnHide.setBackground(new java.awt.Color(121, 163, 177));
        btnHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus (1).png"))); // NOI18N
        btnHide.setContentAreaFilled(false);
        btnHide.setFocusable(false);
        btnHide.setOpaque(true);
        btnHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHideMouseExited(evt);
            }
        });
        panelHeader.add(btnHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 31, 31));

        labelInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelInfo.setForeground(new java.awt.Color(255, 255, 255));
        labelInfo.setText("Uang Kas");
        labelInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelInfoMouseClicked(evt);
            }
        });
        panelHeader.add(labelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 0, 94, 31));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("•");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        panelHeader.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 15, 31));

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 651, -1));

        panelMenu.setBackground(new java.awt.Color(69, 98, 104));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lineRingkasan.setBackground(new java.awt.Color(255, 255, 255));
        lineRingkasan.setOpaque(true);
        panelMenu.add(lineRingkasan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 90, 8));

        lineUangmasuk.setBackground(new java.awt.Color(69, 98, 104));
        lineUangmasuk.setOpaque(true);
        panelMenu.add(lineUangmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 100, 8));

        lineUangkeluar.setBackground(new java.awt.Color(69, 98, 104));
        lineUangkeluar.setOpaque(true);
        panelMenu.add(lineUangkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 100, 8));

        menuUangkeluar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuUangkeluar.setForeground(new java.awt.Color(255, 255, 255));
        menuUangkeluar.setText("Uang Keluar");
        menuUangkeluar.setContentAreaFilled(false);
        menuUangkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuUangkeluar.setFocusable(false);
        menuUangkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUangkeluarActionPerformed(evt);
            }
        });
        panelMenu.add(menuUangkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        menuUangmasuk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuUangmasuk.setForeground(new java.awt.Color(255, 255, 255));
        menuUangmasuk.setText("Uang Masuk");
        menuUangmasuk.setContentAreaFilled(false);
        menuUangmasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuUangmasuk.setFocusable(false);
        menuUangmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUangmasukActionPerformed(evt);
            }
        });
        panelMenu.add(menuUangmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 20, -1, -1));

        menuRingkasan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuRingkasan.setForeground(new java.awt.Color(255, 255, 255));
        menuRingkasan.setText("Ringkasan");
        menuRingkasan.setContentAreaFilled(false);
        menuRingkasan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRingkasan.setFocusable(false);
        menuRingkasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRingkasanActionPerformed(evt);
            }
        });
        panelMenu.add(menuRingkasan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 651, 72));

        pnlBody.setBackground(new java.awt.Color(255, 255, 255));
        pnlBody.setLayout(new java.awt.CardLayout());

        cardRingkasan.setBackground(new java.awt.Color(245, 245, 245));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTotalUangKeluar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTotalUangKeluar.setForeground(new java.awt.Color(121, 163, 177));
        labelTotalUangKeluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalUangKeluar.setText("0");
        jPanel1.add(labelTotalUangKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 169, 176));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total uang keluar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 170, 34));

        labelTotalUangMasuk.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTotalUangMasuk.setForeground(new java.awt.Color(121, 163, 177));
        labelTotalUangMasuk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalUangMasuk.setText("0");
        jPanel1.add(labelTotalUangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 169, 176));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Total uang masuk");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 170, 34));

        labelSisaUang.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelSisaUang.setForeground(new java.awt.Color(121, 163, 177));
        labelSisaUang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelSisaUang, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 169, 176));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Sisa uang kas");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 160, 34));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buy(64).png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 70, 70));

        labelTotalUang_img.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTotalUang_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalUang_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panel2.png"))); // NOI18N
        jPanel1.add(labelTotalUang_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 169, 176));

        panelHeader_totaluang_img.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelHeader_totaluang_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHeader_totaluang_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panelHeader.png"))); // NOI18N
        jPanel1.add(panelHeader_totaluang_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 170, 34));

        labelTotalUang_img1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTotalUang_img1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalUang_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panel2.png"))); // NOI18N
        jPanel1.add(labelTotalUang_img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 169, 176));

        panelHeader_totaluang_img1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelHeader_totaluang_img1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHeader_totaluang_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panelHeader.png"))); // NOI18N
        jPanel1.add(panelHeader_totaluang_img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 170, 34));

        panelHeader_totaluang_img2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelHeader_totaluang_img2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHeader_totaluang_img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panelHeader.png"))); // NOI18N
        jPanel1.add(panelHeader_totaluang_img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 170, 34));

        labelTotalUang_img2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTotalUang_img2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalUang_img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panel2.png"))); // NOI18N
        jPanel1.add(labelTotalUang_img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 169, 176));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cash-payment.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 70, 70));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 70, 70));

        javax.swing.GroupLayout cardRingkasanLayout = new javax.swing.GroupLayout(cardRingkasan);
        cardRingkasan.setLayout(cardRingkasanLayout);
        cardRingkasanLayout.setHorizontalGroup(
            cardRingkasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        cardRingkasanLayout.setVerticalGroup(
            cardRingkasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardRingkasanLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlBody.add(cardRingkasan, "card4");

        cardUangmasuk.setBackground(new java.awt.Color(255, 255, 255));
        cardUangmasuk.setPreferredSize(new java.awt.Dimension(785, 367));
        cardUangmasuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        cardUangmasuk.add(TFbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 55, 223, -1));

        btnSimpan.setBackground(new java.awt.Color(235, 235, 235));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(null);
        btnSimpan.setPreferredSize(new java.awt.Dimension(35, 23));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        cardUangmasuk.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 139, 65, 20));

        btnUbah.setText("Edit");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        cardUangmasuk.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 139, 65, 20));
        cardUangmasuk.add(TFkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 121, 32, -1));

        jLabel1.setText("Nama");
        cardUangmasuk.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 24, -1, -1));

        jLabel2.setText("Jumlah Uang");
        cardUangmasuk.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 55, -1, -1));

        jLabel3.setText("Tanggal");
        cardUangmasuk.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 92, -1, -1));
        cardUangmasuk.add(TFnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 223, -1));

        tabelMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMasuk);

        cardUangmasuk.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 605, 228));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        cardUangmasuk.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 139, 65, 20));

        jLabel14.setText("Cari : ");
        cardUangmasuk.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 22, -1, -1));

        btnCariMasuk.setText("Cari");
        btnCariMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariMasukActionPerformed(evt);
            }
        });
        cardUangmasuk.add(btnCariMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 54, -1, -1));
        cardUangmasuk.add(TFCariMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 229, -1));
        cardUangmasuk.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 220, -1));

        pnlBody.add(cardUangmasuk, "card4");

        cardUangkeluar.setBackground(new java.awt.Color(255, 255, 255));
        cardUangkeluar.setPreferredSize(new java.awt.Dimension(785, 367));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Jumlah uang");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Keperluan");

        TAKeperluan.setColumns(20);
        TAKeperluan.setRows(5);
        jScrollPane2.setViewportView(TAKeperluan);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Rp.");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Tanggal");

        tabelKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKeluarMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelKeluar);

        btnPake.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPake.setText("Simpan");
        btnPake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPakeActionPerformed(evt);
            }
        });

        btnEditPake.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditPake.setText("Edit");
        btnEditPake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPakeActionPerformed(evt);
            }
        });

        btnHapusKeluar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHapusKeluar.setText("Hapus");
        btnHapusKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKeluarActionPerformed(evt);
            }
        });

        jLabel15.setText("Cari :");

        btnCariKeluar.setText("Cari");
        btnCariKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardUangkeluarLayout = new javax.swing.GroupLayout(cardUangkeluar);
        cardUangkeluar.setLayout(cardUangkeluarLayout);
        cardUangkeluarLayout.setHorizontalGroup(
            cardUangkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardUangkeluarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(cardUangkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardUangkeluarLayout.createSequentialGroup()
                        .addGroup(cardUangkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardUangkeluarLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel8))
                            .addComponent(jLabel9)
                            .addGroup(cardUangkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TFkode_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cardUangkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardUangkeluarLayout.createSequentialGroup()
                                .addComponent(btnPake)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditPake)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapusKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TFTerpakai)
                            .addComponent(jScrollPane2)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(cardUangkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cardUangkeluarLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFCariK, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCariKeluar)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(158, 158, 158))
        );
        cardUangkeluarLayout.setVerticalGroup(
            cardUangkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardUangkeluarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(cardUangkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(TFTerpakai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(TFCariK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardUangkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardUangkeluarLayout.createSequentialGroup()
                        .addComponent(btnCariKeluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18))
                    .addGroup(cardUangkeluarLayout.createSequentialGroup()
                        .addGroup(cardUangkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardUangkeluarLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TFkode_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(cardUangkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPake)
                    .addComponent(btnEditPake)
                    .addComponent(btnHapusKeluar))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pnlBody.add(cardUangkeluar, "card5");

        getContentPane().add(pnlBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 650, 430));

        setSize(new java.awt.Dimension(651, 524));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    private void menuRingkasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRingkasanActionPerformed
        lineRingkasan.setBackground(new Color(255,255,255));
        
        lineUangmasuk.setBackground(new Color(69,98,104));
        lineUangkeluar.setBackground(new Color(69,98,104));
        
        pnlBody.removeAll();
        pnlBody.repaint();
        pnlBody.revalidate();
        pnlBody.add(cardRingkasan);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_menuRingkasanActionPerformed

    private void menuUangmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUangmasukActionPerformed
        lineUangmasuk.setBackground(new Color(255,255,255));
        
        lineRingkasan.setBackground(new Color(69,98,104));
        lineUangkeluar.setBackground(new Color(69,98,104));
        
        pnlBody.removeAll();
        pnlBody.repaint();
        pnlBody.revalidate();
        pnlBody.add(cardUangmasuk);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_menuUangmasukActionPerformed

    private void menuUangkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUangkeluarActionPerformed
        lineUangkeluar.setBackground(new Color(255,255,255));
        
        lineRingkasan.setBackground(new Color(69,98,104));
        lineUangmasuk.setBackground(new Color(69,98,104));
        
        pnlBody.removeAll();
        pnlBody.repaint();
        pnlBody.revalidate();
        pnlBody.add(cardUangkeluar);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_menuUangkeluarActionPerformed

    private void btnEditPakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPakeActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/uangkas","root","");
            String sql = "UPDATE uangkeluar SET terpakai='"+TFTerpakai.getText()+"', keperluan='"+TAKeperluan.getText()+"', tanggal_keluar='"+ ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText() +"' WHERE kode_keluar='"+TFkode_keluar.getText()+"'";
            cn.createStatement().executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "edit berhasil");
            tampilkan_uang_keluar();
            resetTextField();
        } catch (SQLException ex) {
            Logger.getLogger(UangKas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "error "+ex);
        }
    }//GEN-LAST:event_btnEditPakeActionPerformed

    private void btnPakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPakeActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/uangkas","root","");
            cn.createStatement().executeUpdate("insert into uangkeluar value(0,'"+TFTerpakai.getText()+"','"+TAKeperluan.getText()+"','"+ ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText() +"')");
            JOptionPane.showMessageDialog(this, "tersimpan");
            tampilkan_uang_keluar();
            resetTextField();

        } catch (SQLException ex) {
            Logger.getLogger(UangKas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPakeActionPerformed

    private void tabelKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKeluarMouseClicked
        int i = tabelKeluar.getSelectedRow();

        if(i > -1){
            TFkode_keluar.setText(model2.getValueAt(i, 0).toString());
            TFTerpakai.setText(model2.getValueAt(i, 1).toString());
            TAKeperluan.setText(model2.getValueAt(i, 2).toString());
//            TFtglkeluar.setText(model2.getValueAt(i, 3).toString());
            ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).setText(model2.getValueAt(i, 3).toString());

        }
    }//GEN-LAST:event_tabelKeluarMouseClicked

    private void tabelMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMasukMouseClicked
        // TODO add your handling code here:
        int i = tabelMasuk.getSelectedRow();

        if(i > -1){
            TFkode.setText(model.getValueAt(i, 0).toString());
            TFnama.setText(model.getValueAt(i, 1).toString());
            TFbayar.setText(model.getValueAt(i, 2).toString());
            //TFtgl.setText(model.getValueAt(i, 3).toString());
            
            ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(model.getValueAt(i, 3).toString());
            
            

        }
    }//GEN-LAST:event_tabelMasukMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/uangkas","root","");
            String sql = "UPDATE uangmasuk SET pembayar='"+TFnama.getText()+"', uang_masuk='"+TFbayar.getText()+"', tanggal_bayar='"+ ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText() +"' WHERE kode='"+TFkode.getText()+"'";
            cn.createStatement().executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "edit berhasil");
            tampilkan();
            resetTextField();
        } catch (SQLException ex) {
            Logger.getLogger(UangKas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "error "+ex);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/uangkas","root","");
            cn.createStatement().executeUpdate("insert into uangmasuk value(0,'"+TFnama.getText()+"','"+TFbayar.getText()+"','"+ ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText() +"')");
            JOptionPane.showMessageDialog(this, "tersimpan");
            tampilkan();
            resetTextField();

        } catch (SQLException ex) {
            Logger.getLogger(UangKas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/uangkas","root","");
            String sql = "DELETE FROM uangmasuk WHERE kode='"+TFkode.getText()+"'";
            cn.createStatement().executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "hapus berhasil");
            tampilkan();
            resetTextField();
        } catch (SQLException ex) {
            Logger.getLogger(UangKas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "error "+ex);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnHapusKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKeluarActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/uangkas","root","");
            String sql = "DELETE FROM uangkeluar WHERE kode_keluar='"+TFkode_keluar.getText()+"'";
            cn.createStatement().executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "hapus berhasil");
            tampilkan_uang_keluar();
            resetTextField();
        } catch (SQLException ex) {
            Logger.getLogger(UangKas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "error "+ex);
        }
    }//GEN-LAST:event_btnHapusKeluarActionPerformed

    private void btnCariMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariMasukActionPerformed
        tampilkan();
    }//GEN-LAST:event_btnCariMasukActionPerformed

    private void btnCariKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariKeluarActionPerformed
        tampilkan_uang_keluar();
    }//GEN-LAST:event_btnCariKeluarActionPerformed

    private void panelHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderMousePressed
        Xmouse =  evt.getX();
        Ymouse =  evt.getY();
    }//GEN-LAST:event_panelHeaderMousePressed

    private void panelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderMouseDragged
        if(maximized){
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x - Xmouse, y - Ymouse);
        }
    }//GEN-LAST:event_panelHeaderMouseDragged

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        this.dispose();
        Format format = new Format();
        format.setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void labelInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelInfoMouseClicked
        new AboutUs().setVisible(true);
    }//GEN-LAST:event_labelInfoMouseClicked

    private void btnHideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHideMouseExited
        //after hover
        btnHide.setBackground(new Color(121,163,177));
    }//GEN-LAST:event_btnHideMouseExited

    private void btnHideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHideMouseEntered
        btnHide.setBackground(new Color(71, 110, 122));
    }//GEN-LAST:event_btnHideMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        //after hover
        btnExit.setBackground(new Color(121,163,177));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(new Color(232, 17, 35));
    }//GEN-LAST:event_btnExitMouseEntered

    // exit
    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHideMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnHideMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UangKas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TAKeperluan;
    private javax.swing.JTextField TFCariK;
    private javax.swing.JTextField TFCariMasuk;
    private javax.swing.JTextField TFTerpakai;
    private javax.swing.JTextField TFbayar;
    private javax.swing.JTextField TFkode;
    private javax.swing.JTextField TFkode_keluar;
    private javax.swing.JTextField TFnama;
    private javax.swing.JButton btnCariKeluar;
    private javax.swing.JButton btnCariMasuk;
    private javax.swing.JButton btnEditPake;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapusKeluar;
    private javax.swing.JButton btnHide;
    private javax.swing.JButton btnPake;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel cardRingkasan;
    private javax.swing.JPanel cardUangkeluar;
    private javax.swing.JPanel cardUangmasuk;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JLabel labelSisaUang;
    private javax.swing.JLabel labelTotalUangKeluar;
    private javax.swing.JLabel labelTotalUangMasuk;
    private javax.swing.JLabel labelTotalUang_img;
    private javax.swing.JLabel labelTotalUang_img1;
    private javax.swing.JLabel labelTotalUang_img2;
    private javax.swing.JLabel lineRingkasan;
    private javax.swing.JLabel lineUangkeluar;
    private javax.swing.JLabel lineUangmasuk;
    private javax.swing.JButton menuRingkasan;
    private javax.swing.JButton menuUangkeluar;
    private javax.swing.JButton menuUangmasuk;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JLabel panelHeader_totaluang_img;
    private javax.swing.JLabel panelHeader_totaluang_img1;
    private javax.swing.JLabel panelHeader_totaluang_img2;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JTable tabelKeluar;
    private javax.swing.JTable tabelMasuk;
    // End of variables declaration//GEN-END:variables
    
    // untuk menampilkan data uang masuk
    public void tampilkan(){
        
        uang_masuk();
        sisa_uang();
        
        // untuk menghapus data sebelumnya ketika data yang baru di tampilkan
        // jika tidak data akan terduplikat di tabel
        int row = tabelMasuk.getRowCount();
        for(int i = 0 ; i < row ; i++){
            model.removeRow(0);
        }
        
        this.TFkode.setVisible(false);
        String tempCari = TFCariMasuk.getText();
        int no = 1;
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/uangkas","root","");
            ResultSet rs = cn.createStatement().executeQuery("select * from uangmasuk WHERE pembayar LIKE '%"+tempCari+"%'");
            
            while(rs.next()){
                //String data [] = {rs.getString,rs.getString(1),rs.getString(2),rs.getString(3)};
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(UangKas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void tampilkan_uang_keluar(){
        
        uang_keluar();
        sisa_uang();
        
        int row = tabelKeluar.getRowCount();
        for(int i = 0 ; i < row ; i++){
            model2.removeRow(0);
        }
        this.TFkode_keluar.setVisible(false);
        String tempCari = TFCariK.getText();
        int no = 1;
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/uangkas","root","");
            ResultSet rs = cn.createStatement().executeQuery("select * from uangkeluar WHERE keperluan LIKE '%"+tempCari+"%'");
            
            while(rs.next()){
                //String data [] = {rs.getString,rs.getString(1),rs.getString(2),rs.getString(3)};
                model2.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(UangKas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // untuk mereset textfield
    private void resetTextField(){
        TFkode.setText(null);
        TFnama.setText(null);
        TFbayar.setText(null);
        //TFtgl.setText(null);
        ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(null);
        TFTerpakai.setText(null);
        TAKeperluan.setText(null);
//        TFtglkeluar.setText(null);
        ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).setText(null);
        
    }
    
    // untuk menampilkan total uang masuk
    private void uang_masuk(){
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/uangkas","root","");
            ResultSet rs = cn.createStatement().executeQuery("select sum(uang_masuk) from uangmasuk");
            if(rs.next()){
                String s = rs.getString("sum(uang_masuk)");
                labelTotalUangMasuk.setText(s);
            }
        } catch (SQLException ex) {
            //Logger.getLogger(Ringkasan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "error "+ex);
        }
    }
    
    private void uang_keluar(){
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/uangkas","root","");
            ResultSet rs = cn.createStatement().executeQuery("select sum(terpakai) from uangkeluar");
            if(rs.next()){
                String s = rs.getString("sum(terpakai)");
                labelTotalUangKeluar.setText(s);
                
            }
        } catch (SQLException ex) {
            //Logger.getLogger(Ringkasan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "error "+ex);
        }
        
       
    }
    
    private void sisa_uang(){
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/uangkas","root","");
            ResultSet rs = cn.createStatement().executeQuery("select sum(terpakai) from uangkeluar");
            ResultSet rs2 = cn.createStatement().executeQuery("select sum(uang_masuk) from uangmasuk");
            if(rs.next() & rs2.next()){
                int s = rs.getInt("sum(terpakai)");
                int s2 = rs2.getInt("sum(uang_masuk)");
                int sisa = s2 - s;
                labelSisaUang.setText(Integer.toString(sisa));
                
            }
        } catch (SQLException ex) {
            //Logger.getLogger(Ringkasan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "error "+ex);
        }
    }
    
    public void muatUlang(){
        tampilkan();
        tampilkan_uang_keluar();
    }
    
}